name: openpay
description: Openpay dart package.
version: 0.0.1
homepage: https://github.com/kiwi-bop/openpay

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4

dev_dependencies:
